### ISSUE TITLE
Troika Layout and Text

### ISSUE THREAD

**Issue by jmatsushita** [react-spring/drei#101]
Hi there, it's really great that @drcmda amd @lojjic are working to improve interop between r3f and troika! Following up on the conversation on r3f and troika layout in this issue https://github.com/react-spring/drei/pull/20#issuecomment-632173587 from @skuteli. 

I'm trying to [add troika text (via the drei module) to a Flex layout](https://codesandbox.io/s/yoga-r3f-troika-flex-text-50kht?file=/src/App.js) but I can't get the text

Note that you need to interact with the scene once for the text to render [because of this issue](https://github.com/react-spring/drei/issues/99).

Much appreciation for setting up the building blocks for programming 3d on the web (and mobile [with react-native](https://github.com/react-spring/drei/issues/19) hopefully). With layout (wow yoga in a wasm worker) and text (wow its fast and with carets and selections!), and the declarative approach of `react-three-fiber` it becomes a really exciting space for 3d UIs!

**Comment by skuteli** [comment]
Hi:) 
<Flex> component doesn't work with Troika's text at the moment.
The reason for this is that it uses boundingBox for measurement of item's dimensions, and this is not working with Troika's text geometry - only bounding sphere is accessible.
Ideally we would use the measurement function provided by troika, but this is not trivial due to different lifecycle (at least I tried it and failed)
One solution to this would be to ask @lojic to make troika text work with bounding box - then flex should start working ootb. 
Any help appreciated!

**Comment by jmatsushita** [comment]
Thanks for the pointer! I've had a look and added `boundingBox`es around the text, then I created a helper component `<Paragraph>` to allow `<Box>` to pick up the [text properties needed by Yoga on `styleNodes`](https://github.com/protectwise/troika/blob/1b52fc9a9a5a3ae03c27d0d12a0f62c3d73fe599/packages/troika-flex-layout/src/FlexLayoutProcessor.js#L218) (for now in a fork of `troika-three-text` here https://github.com/jmatsushita/troika-three-text so I could test in a sandbox).

It's not very straightforward to debug in worker threads from Chrome dev tools, so I'm not sure that the `measure` function is actually called in [the FontProcessor](https://github.com/protectwise/troika/blob/master/packages/troika-three-text/src/worker/FontProcessor.js#L550) or if I just missed something with how to get the Yoga `width` and `height` computation.  

My current exploration is in this sandbox: https://codesandbox.io/s/yoga-r3f-troika-flex-text-50kht

**Comment by lojjic** [comment]
@jmatsushita Nice progress on that! I tried playing with that CSB briefly too but you got it further than I did.

I think you're close. A couple things I see:
- For text nodes you need to make sure to skip the useLayoutEffect logic that sets the styleNode's width/height to measured dimensions. Since those measured dimensions for text nodes will initially be 0x0, that forces a zero-sized flex node and skips measurement of the text.
- There's a difference between the `maxWidth` used for flex layout calculation, and the `maxWidth` applied to the rendered `Text` object. The former should be the user's value as you've done, but the latter should be the _calculated width_ after the layout completes.

**Comment by jmatsushita** [comment]
Thanks a ton for the assist!!

> For text nodes you need to make sure to skip the useLayoutEffect logic 
That change pretty much solved it! Great. 

> There's a difference between the `maxWidth` used for flex layout calculation, and the `maxWidth`
Ah yes, that's a nice trap :) I think I addressed it by leaving the `flexProps.maxWidth` alone.

Is it correct that the reason there is no `boundingBox` calculation on text is that in troika text is meant to be laid out in a UI Facade which will act as a container for the text and pass through its constraints?

Is it still useful to add the `boundingBox` for text meshes? I've submitted [a PR for it](https://github.com/protectwise/troika/pull/74), and It seems that it wouldn't add actually any memory (just a small bunch of pointers) or computation overhead at all.  

@lojjic in the previous thread you mentioned 
> I do have some other thoughts on the API

Could you and @drcmda elaborate a bit on what you have in store so that what I do can be migrated smoothly? 

By the way, I've searched quite a bit for an equivalent of flex in 3d a while back and I was quite surprised not to find anything. Do you know of other high-level constraint languages for 3d layout? Also I thing that maybe in 3d yoga we could wrap around for cylindrical (maybe spherical) layouts? Interesting yoga poses, ta dam chiing. 🥁

**Comment by jmatsushita** [comment]
Ah I see not all is well [in the sandbox](https://codesandbox.io/s/yoga-r3f-troika-flex-text-50kht)

![image](https://user-images.githubusercontent.com/356097/91402019-3f418c00-e841-11ea-8cda-de0344184292.png)

I misunderstood what you meant with `maxWidth` so I'm looking at it again.

**Comment by stephencorwin** [comment]
@jmatsushita we just released https://github.com/react-spring/react-three-flex which is a wrapper around yoga-layout.

**Comment by stephencorwin** [comment]
Closing this for now as I believe react-three-flex helps solve these issues. If you wish to continue the discussion, please reopen or join us on discord:
[![Discord Shield](https://discordapp.com/api/guilds/740090768164651008/widget.png?style=banner2)](https://discord.gg/ZZjjNvJ)
