### ISSUE TITLE
Text with custom material

### ISSUE THREAD

**Issue by lojjic** [react-spring/drei#15]
Thanks for the `Text` wrapper for Troika's TextMesh!

Stylistically I like the choice to specify the text content as the JSX element's content, that feels very HTML-ey even if you can't do inline markup.

However it seems that this removes the ability to specify a custom material declaratively e.g. with a `<meshStandardMaterial attach="material" .../>` child. The ability to use any material is one of troika-3d-text's best features, and r3f's declarative child approach for materials is so clean, it would be a shame to lose that integration. Is there a way to preserve it?

**Comment by drcmda** [comment]
thanks for this awesome library! i was thinking about if it makes sense at all to wrap it since troika-3d-text is so easy to use and lean already standalone. i guess it's just bc of types, extend and children. but i will be using it practically all day now. i didn't think of the material, i'll fix it.

btw, have you thought about crossing troika-3d-text with yoga? it's like a cross platform css.

**Comment by lojjic** [comment]
See PR #20 for addl discussion.

**Comment by lojjic** [comment]
Think this was implemented a while ago. Closing.
