### ISSUE TITLE
HTML Component loses Context

### ISSUE THREAD

**Issue by giulioz** [react-spring/drei#17]
When working with HTML component you loose all the React contexts, breaking libraries like MaterialUI that relies on theming.
It's possible to find another solution that doesn't involve calling `ReactDOM.render`, maybe using portals?

**Comment by drcmda** [comment]
i would love that, but it's hard to do i guess. portal cant render from one reconciler into another, if you create a portal inside canvas, it expects threejs elements, not divs and spans. and even if, context wouldnt even go into <Canvas>. i hope the react team will figure this out at some point, because mixing reconcilers quite jarring.
