### ISSUE TITLE
Getting the sound object through <PositionalAudio />

### ISSUE THREAD

**Issue by gsimone** [react-spring/drei#71]
I tried whipping up an AudioAnalyser demo using <PositionalAudio /> ( from this discussion https://github.com/react-spring/react-three-fiber/discussions/520 ) but there seems to be a problem accessing the ref

Sandbox here: https://codesandbox.io/s/r3f-audo-analyser-cmieg

I had to work around it by checking in useFrame if the ref was defined:

```jsx
useFrame(() => {
    if (analyser.current) {
      const data = analyser.current.getAverageFrequency();
     ...
    } else if (sound.current) {
      analyser.current = new THREE.AudioAnalyser(sound.current, 32);
    }
  });
```

This smells really bad, I'm not sure if I'm missing something

**Comment by drcmda** [comment]
Oh, that would be unfortunate. I will look into it when I have time

**Comment by drcmda** [comment]
@gsimone @davidalexandercurrie

positionalAudio is an async component, it uses audioloader, which runs a fetch request. so the ref on it will become active once the loader has finished loading. in other words you can't possibly catch it with useEffect.

but you can using suspense in concurrent mode, because all components inside a suspense block are only rendered once all suspensions have been lifted. 

https://codesandbox.io/s/r3f-audo-analyser-38vb8?file=/src/App.js
